### ISSUE TITLE
Sending lyrics to PowerAmp does not save .lrc file

### ISSUE THREAD

**Issue by thousandsofthem** [abhishekabhi789/LyricsForPoweramp#18]
Creating separate issue to track it.

### Scenario 1: automatic searching for lyrics from PowerAmp:

Current behavior: hard to understand what's going on, but usually i see nothing is found

### Scenario 2: search from notification 

Steps to reproduce:
- play song in PowerAmp 
- click "lyrics" button in UI
- see nothing happens 
- tap on notification "tap here to manually search"
- confirm search with "Search"
- see results
- click on "check" button
- see screenshot as following:

![Image](https://github.com/user-attachments/assets/d593b025-0c89-4b8c-ad0c-b7a77b27c4f0)

- no new files on disk

Expected behavior: .lrc file saved alongside music file

### Scenario 3: search from library in latest google (beta) build

Saving .lrc files works but very clunky since i need to search for a file again from scratch (also file location is not visible)

Versions:
App: latest available google beta build, 1.5.7-play (same behavior in 1.5 GitHub version)
Android: 15

P.S. I'm not against paying some premium for a working app, some visible option like this would be totally ok

**Comment by abhishekabhi789** [comment]
Hi there, thanks for the report and sorry for the inconvenience.
This error occurs when the plugin app cannot determine where to save the lyrics file. It would be helpful if you could share the device log when the problem occurs.
Thanks.

**Comment by thousandsofthem** [comment]
Hello! How do i do that? `adb logcat` produces a lot of noise, and i don't see any relevant lines, no mention of lyricsforpoweramp

**Comment by thousandsofthem** [comment]
Tried it again, got pid and exactly zero log lines matching that pid

**Comment by thousandsofthem** [comment]
Search from notification area: always showing an error.

Search from PowerAmp, lyrics screen, when lyrics already found, ">>" icon on top right corner: no error

**Comment by abhishekabhi789** [comment]
The PID may be changed during the test. It can happen,
Here's an alternate command `adb logcat -s "StorageHelper","PowerampApiHelper" > l4pa.log` 
Just run this and check the file.

**Comment by thousandsofthem** [comment]
> The PID may be changed during the test. It can happen

nope, still the same.

> Here's an alternate command

Tried it, no logs either

**Comment by abhishekabhi789** [comment]
Hi again, the issue was due to a missing file path parameter in the notification. Now it seems fixed.
I've published a new Play Store version (1.5.8), but it may take some time to go live.
Here's the internal share link: https://play.google.com/apps/test/io.github.abhishekabhi789.lyricsforpoweramp/33
You might need to uninstall the existing apk to install this one. Otherwise, you can wait for the next release.
Thanks for the report and help.

**Comment by thousandsofthem** [comment]
Thanks a lot! Internal link don't work though, before and after uninstalling. Says "not found". I'll wait for release

**Comment by thousandsofthem** [comment]
I think this issue needs to be reopened.
Got 1.5.8-play finally, issue persists. Also, discovered weird behavior: this app creates additional folders for some reason.

Full path is like this:
```
Music/The Offspring/1998 Americana/12 Americana.opus
```

![Image](https://github.com/user-attachments/assets/e474c6dd-1b5f-48b9-a538-5c1e364e124d)

![Image](https://github.com/user-attachments/assets/77398112-ae4e-4765-b7a1-be972d8a328b)

**Comment by abhishekabhi789** [comment]
When I tested the same track(same track's mp3 file renamed to opus) I found it saved the lyrics without any issue.
```
06:39:29.709 30446-30501 StorageHelper            io....sforpoweramp.debug  D  writeLyricsFile: track file path primary/Music/The Offspring/1998 Americana/12 Americana.opus
06:39:29.870 30446-30501 PowerampApiHelper        io....sforpoweramp.debug  I  sendLyricResponse: save to storage SUCCESS
```
I've granted access to `primary/Music` in the plugin app. 
Are you using an external storage device? Cause I never tested the app with external storages.

**Comment by thousandsofthem** [comment]
No, this is internal storage, all music inside `primary/Music`, access granted. Also it works from Library. Also, sometimes it works as expected from notification. "Sometimes" does not depend on exact song, no idea what's the difference. .mp3 format or different folder name don't change anything.

Did you figure out how it even possible to have new folder created in the middle of the path?
```
Music/The Offspring/1998 Americana/12 Americana.opus
Music/The Offspring (1)/1998 Americana/12 Americana.opus
```
that's weird

**Comment by abhishekabhi789** [comment]
https://github.com/abhishekabhi789/LyricsForPoweramp/blob/763483a10ffbec86df1dae17233fa5c0d8f75c45/app/src/main/java/io/github/abhishekabhi789/lyricsforpoweramp/helpers/StorageHelper.kt#L54-L62
This is how the app navigate to the target foler inside permission granted root folder.
The `findFile()` returns `null` so it attempts to create a new folder using `createDirectory()`. However, since the folder already exists, it appends the number to the name to avoid collision.

I had added `createDirectory()` during early development (for testing) and forgot to remove it.
The expected behaviour should be to abort the task if it can't navigate to the target folder.

I'm not entirely sure why `findFile()` fails. It could be due to a naming issue or a system-related problem.

**Comment by thousandsofthem** [comment]
Are there any error text in the case it fails?

Doing more tests today, last hour it worked 100% of attempts with no errors. Still have no idea what triggers an error
